server:
  servlet:
    session:
      timeout: 24h

encryption:
  password: alkj28lskd
  salt: A4F1C52ED7AA56

spring:
  application:
    name: cloud-storage
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 300MB
  redis:
    host: localhost
    port: 6379    
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstore
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
        